- name: install Windows Updates
  hosts: all
  vars:
    hotfix_download_location: "{{ ansible_env.TEMP }}"
    hotfixes:
      - kb: KB2883201
        file: Windows8-RT-KB2883201-x64.msu
        url: https://download.microsoft.com/download/C/A/A/CAA19F2F-ED39-4729-BB13-8190290473C1/Windows8-RT-KB2883201-x64.msu

  tasks:
    - block:
        - name: ensure Windows ADK with DISM is installed
          win_chocolatey:
            name: windows-adk-deploy
            state: present
            version: 10.0.17134.0
          register: install_windows_adk_deploy

        - name: ensure PATH contains Windows ADK
          win_path:
            scope: machine
            state: present
            elements: "C:\\Program Files (x86)\\Windows Kits\\10\\Assessment and Deployment Kit\\Deployment Tools\\amd64\\DISM"
      when: "'2008' in ansible_distribution"

    - name: download hotfix
      win_get_url:
        url: '{{ item.url }}'
        dest: '{{ hotfix_download_location }}\{{ item.file }}'
      loop: "{{ hotfixes }}"

    - name: install hotfix
      win_hotfix:
        hotfix_kb: '{{ item.kb }}'
        source: '{{ hotfix_download_location }}\{{ item.file }}'
        state: present
      register: hotfix_install
      loop: "{{ hotfixes }}"

    - name: debug hotfix installation result
      debug:
        var: hotfix_install