---

# On Windows 2008 R2 and Windows 2012 hosts it may be necessary to update TLS to v1.2 as credssp used 1.2 by default
# See the following pages for explanation:
# https://docs.ansible.com/ansible/latest/user_guide/windows_winrm.html#id17
# https://docs.ansible.com/ansible/latest/user_guide/windows_winrm.html#winrm-tls12
# This playbook applies the hotfix and enables TLSv1.2
# You can run the following command from an Ansible control point (i.e Tower node) or any linux/mac to test the version:
# openssl s_client -connect <hostname>:5986

- name: Enable credssp TLS v1.2
  hosts: all
  vars:
    hotfix_download_location: "{{ ansible_env.TEMP }}"
    hotfixes_group_1:
      - kb: KB3080079
        file: Windows6.1-KB3080079-x64.msu
        url: https://download.microsoft.com/download/F/4/1/F4154AD2-2119-48B4-BF99-CC15F68E110D/Windows6.1-KB3080079-x64.msu

  tasks:
    - name: ensure Windows ADK with DISM is installed
      win_chocolatey:
        name: windows-adk-deploy
        state: present
        version: 10.0.17134.0
      register: install_windows_adk_deploy

    - name: ensure PATH contains Windows ADK
      win_path:
        scope: machine
        state: present
        elements: "C:\\Program Files (x86)\\Windows Kits\\10\\Assessment and Deployment Kit\\Deployment Tools\\amd64\\DISM"

    - name: download hotfix group 1
      win_get_url:
        url: '{{ item.url }}'
        dest: '{{ hotfix_download_location }}\{{ item.file }}'
      loop: "{{ hotfixes_group_1 }}"

    - name: install hotfix group 1
      win_hotfix:
        source: '{{ hotfix_download_location }}\{{ item.file }}'
        state: present
      register: hotfix_install_group_1
      loop: "{{ hotfixes_group_1 }}"

    - name: debug hotfix installation result
      debug:
        var: hotfix_install_group_1

    - name: ensure hotfix file is removed (group 1)
      win_file:
        path: '{{ hotfix_download_location }}\{{ item.file }}'
        state: absent
      loop: "{{ hotfixes_group_1 }}"

    - name: enable TLSv1.2 support
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\{{ item.type }}
        name: '{{ item.property }}'
        data: '{{ item.value }}'
        type: dword
        state: present
      register: enable_tls12
      loop:
        - type: Server
          property: Enabled
          value: 1
        - type: Server
          property: DisabledByDefault
          value: 0
        - type: Client
          property: Enabled
          value: 1
        - type: Client
          property: DisabledByDefault
          value: 0

    - name: reboot if TLS config was applied
      win_reboot:
      when: enable_tls12 is changed