---
- name: Remove Windows Servers
  hosts: all
  gather_facts: false
  connection: local
  vars:
    ansible_ssh_password: ""
  become: false
  vars_files:
    - node-config/nodes-kubevirt.yml

  roles:
    - role: ansible-role-kubevirt
      role_action: deprovision
      delegate_to: localhost
      run_once: true
