---
- name: Deploy Windows Servers on Azure
  hosts: all
  gather_facts: false
  connection: local
  become: false
  vars:
    ansible_port: 5986
  vars_files:
    - node-config/nodes-azure.yml

  roles:
    - ansible-role-azure
