---
- name: Deploy Windows Servers
  hosts: all
  gather_facts: false
  connection: local
  become: false
  vars:
    ansible_port: 5986
  vars_files:
    - node-config/nodes-wsus-server-vmware.yml

  roles:
    - ansible-role-vmware
