---
- name: Deploy Windows Servers
  hosts: all
  gather_facts: false
  connection: local
  become: false
  vars_files:
    - node-config/nodes-wsus-server-kubevirt.yml

  roles:
    - ansible-role-kubevirt
