- name: Deploy Windows Servers
  hosts: all
  gather_facts: False
  connection: local
  become: no
  vars:
    ansible_port: 5986
  vars_files:
    - node-config/nodes-wsus-server-mgmt-vmware.yml

  roles:
  - ansible-role-vmware