- name: Stop IIS
  hosts: 'vmware_tag_env_test:&vmware_tag_iis_app:&vmware_tag_group_abc'
  tasks:
    - name: Ensure iis service is stopped
      win_dsc:
        resource_name: service
        name: W3Svc
        state: stopped

- name: install Windows Updates
  hosts: 'vmware_tag_env_test'

  roles:
    - configure-update
    - update-windows

- name: Start IIS
  hosts: 'vmware_tag_env_test:&vmware_tag_iis_app:&vmware_tag_group_abc'
  tasks:
    - name: Ensure iis service is started
      win_dsc:
        resource_name: service
        name: W3Svc
        state: started

    - name: proper response from iis is received
      win_uri:
        url: http://{{ inventory_hostname }}/
        return_content: yes
        validate_certs: no
      register: response
      until: site_title in response.content
      retries: 10
      delay: 1
      ignore_errors: yes

    - name: output url
      debug:
        msg: 'application is available at http://{{ ansible_host }}/'
      when: response is success